# Generated by Django 4.2 on 2024-09-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
