# Generated by Django 4.2 on 2024-09-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_alter_project_task_asignee"),
        ("authorization", "0003_customuser_is_staff_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.certificate",
            ),
        ),
    ]
