# Generated by Django 4.2 on 2024-09-08 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0004_alter_customuser_certificate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
