# Generated by Django 4.2 on 2024-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[("In progress", "In progress"), ("Completed", "Completed")],
                max_length=12,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Meeting", "Зустріч"),
                    ("Code Review", "Код рев'ю"),
                    ("Progress Update", "Оновлення прогресу"),
                ],
                max_length=16,
                null=True,
                verbose_name="Тип події",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Not started", "Not started"),
                    ("Finished", "Finished"),
                ],
                max_length=13,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                max_length=6,
                verbose_name="Приорітет задачі",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("In progress", "In progress"), ("Completed", "Completed")],
                max_length=12,
                verbose_name="Статус",
            ),
        ),
    ]
