# Generated by Django 4.2 on 2024-09-07 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0003_alter_assignment_status_alter_event_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="task_asignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_lead",
                to=settings.AUTH_USER_MODEL,
                verbose_name="TeamLead",
            ),
        ),
    ]
