# Generated by Django 4.2 on 2024-09-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_alter_project_task_asignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="preview",
            field=models.URLField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Посилання на зображення для прев'ю",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_link",
            field=models.URLField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Посилання на проєкт",
            ),
        ),
    ]
