# Generated by Django 4.2 on 2024-09-08 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0005_alter_project_preview_alter_project_project_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("FRONT-END", "Front-End"),
                            ("BACK-END", "Back-End"),
                            ("QA-TESTER", "QA-tester"),
                            ("DESIGNER", "Designer"),
                            ("DATA SCRAPER", "Data Scraper"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Спеціалізація",
                    ),
                ),
                ("discord_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
