# Generated by Django 4.2 on 2024-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="projects",
            field=models.ManyToManyField(null=True, to="crm.project"),
        ),
    ]
