# Generated by Django 4.2 on 2024-09-25 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0007_profile_full_name_profile_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="projects",
            field=models.ManyToManyField(blank=True, null=True, to="crm.project"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
