# Generated by Django 4.2.5 on 2024-09-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0009_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "В розробці"),
                    ("Not started", "Не розпочато"),
                    ("Finished", "Завершено"),
                ],
                max_length=13,
                null=True,
            ),
        ),
    ]
