# Generated by Django 4.2.5 on 2024-10-16 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0010_alter_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="projects",
        ),
    ]
