# Generated by Django 4.2 on 2024-10-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0011_remove_profile_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("admin", "Адміністратор"), ("user", "Користувач")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="crm.project",
            ),
        ),
    ]
